//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceSQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceSQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pharmacy.ResourceSQL", typeof(ResourceSQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[sp_AddQuantity]
        ///	@id INT,
        ///	@quantity INT
        ///AS
        ///BEGIN
        ///	UPDATE Product
        ///	SET Quantity = @quantity
        ///	WHERE Id = @id
        ///END.
        /// </summary>
        public static string AddProdQuantity {
            get {
                return ResourceManager.GetString("AddProdQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[sp_AddQuantity].
        /// </summary>
        public static string AddProdQuantityName {
            get {
                return ResourceManager.GetString("AddProdQuantityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[sp_BillReport]
        ///	@billId INT	
        ///AS
        ///BEGIN
        ///	SELECT s.*, p.Name, u.First_Name+&apos; &apos;+u.Last_Name AS Nombre, u.Ci, u.Email FROM SaleDetails s, Bills b, Products p, AspNetUsers u WHERE p.Id LIKE s.ProductId AND u.Id LIKE b.UserId AND s.BillId LIKE b.Id AND b.Id LIKE @billId
        ///END.
        /// </summary>
        public static string BillReport {
            get {
                return ResourceManager.GetString("BillReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[sp_BillReport].
        /// </summary>
        public static string BillReportName {
            get {
                return ResourceManager.GetString("BillReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[sp_CreateBill]
        ///	@id INT,
        ///	@userId NVARCHAR(128),
        ///	@saleId INT,
        ///	@sellerId NVARCHAR(128),
        ///	@create_at DATE,
        ///	@subTotal REAL,
        ///	@discount REAL,
        ///	@bonus REAL,
        ///	@totalIva INT,
        ///	@total REAL
        ///AS
        ///BEGIN
        ///	SET IDENTITY_INSERT Bills ON
        ///	INSERT Bills(Id,UserId,SaleId,SellerId,Create_at,SubTotal,Discount,Bonus,TotalIVA,Total) VALUES  (@id,@userId,@saleId,@sellerId,@create_at,@subTotal,@discount,@bonus,@totalIva,@total)
        ///	SET IDENTITY_INSERT Bills OFF
        ///END.
        /// </summary>
        public static string CreateBill {
            get {
                return ResourceManager.GetString("CreateBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[sp_CreateBill].
        /// </summary>
        public static string CreateBillName {
            get {
                return ResourceManager.GetString("CreateBillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[sp_CreateBookinDetails]
        ///	@id INT,
        ///	@subTotal REAL,
        ///	@quantity INT,
        ///	@bookingid INT,
        ///	@productid INT
        ///AS
        ///Begin
        ///	SET IDENTITY_INSERT BookingsDetails ON
        ///	INSERT BookingsDetails(Id,SubTotal,Quantity,BookingId,ProductId) VALUES  (@id,@subTotal,@quantity,@bookingid,@productid)
        ///	SET IDENTITY_INSERT BookingsDetails OFF
        ///END.
        /// </summary>
        public static string CreateBookingDetails {
            get {
                return ResourceManager.GetString("CreateBookingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[sp_CreateBookingDetails].
        /// </summary>
        public static string CreateBookingDetailsName {
            get {
                return ResourceManager.GetString("CreateBookingDetailsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[sp_CreateBookings].
        /// </summary>
        public static string CreateBookingName {
            get {
                return ResourceManager.GetString("CreateBookingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[sp_CreateBookings]
        ///	@id INT,
        ///	@total REAL,
        ///	@create_at DATE,
        ///	@userId NVARCHAR(128)
        ///AS
        ///Begin
        ///	SET IDENTITY_INSERT Bookings ON
        ///	INSERT Bookings(Id,Total,Create_at,UserId) VALUES(@id,@total,@create_at,@userId)
        ///	SET IDENTITY_INSERT Bookings OFF
        ///END.
        /// </summary>
        public static string CreateBookings {
            get {
                return ResourceManager.GetString("CreateBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[sp_CreateSaleDetails]
        ///	@id INT,
        ///	@billId INT,
        ///	@productId INT,
        ///	@quantity INT,
        ///	@unitPrice REAL,
        ///	@discount REAL,
        ///	@subTotal REAL,
        ///	@iva REAL,
        ///	@netTotal INT
        ///AS
        ///Begin
        ///	SET IDENTITY_INSERT SaleDetails ON
        ///	INSERT SaleDetails(Id,BillId,ProductId,Quantity,UnitPrice,Discount,SubTotal,IVA,NetTotal) VALUES  (@id,@billId,@productId,@quantity,@unitPrice,@discount,@subTotal,@iva,@netTotal)
        ///	SET IDENTITY_INSERT SaleDetails OFF
        ///END.
        /// </summary>
        public static string CreateSaleDetails {
            get {
                return ResourceManager.GetString("CreateSaleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[sp_CreateSaleDetails].
        /// </summary>
        public static string CreateSaleDetailsName {
            get {
                return ResourceManager.GetString("CreateSaleDetailsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE[dbo].[sp_DeleteRole]
        ///	@id AS NVARCHAR(128)
        ///AS
        ///BEGIN
        ///    DELETE FROM [dbo].[AspNetRoles]
        ///	WHERE Id=@id
        ///END.
        /// </summary>
        public static string DeleteRole {
            get {
                return ResourceManager.GetString("DeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[sp_DeleteRole].
        /// </summary>
        public static string DeleteRoleName {
            get {
                return ResourceManager.GetString("DeleteRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[sp_InsertRole]
        ///	@id AS NVARCHAR(128),
        ///	@name AS NVARCHAR(256)   
        ///AS
        ///BEGIN
        ///	INSERT [dbo].[AspNetRoles]VALUES (@id,@name)
        ///END.
        /// </summary>
        public static string InsertRole {
            get {
                return ResourceManager.GetString("InsertRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[sp_InsertRole].
        /// </summary>
        public static string InsertRoleName {
            get {
                return ResourceManager.GetString("InsertRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[sp_ListRole]
        ///
        ///AS
        ///Begin
        ///	SELECT [Name]
        ///	FROM AspNetRoles
        ///END.
        /// </summary>
        public static string ListRole {
            get {
                return ResourceManager.GetString("ListRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[sp_ListRole].
        /// </summary>
        public static string ListRoleName {
            get {
                return ResourceManager.GetString("ListRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[sp_ListUserRole]
        ///
        ///AS
        ///Begin
        ///	SELECT [u].[First_Name], [u].[Last_Name], [u].[Ci],[r].[Name]
        ///	FROM AspNetUsers as u, AspNetRoles as r,AspNetUserRoles as a
        ///	WHERE u.Id=a.UserId AND a.RoleId=r.Id
        ///END.
        /// </summary>
        public static string ListUserRole {
            get {
                return ResourceManager.GetString("ListUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[sp_ListUserRole].
        /// </summary>
        public static string ListUserRoleName {
            get {
                return ResourceManager.GetString("ListUserRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[sp_ListUsers]
        ///
        ///AS
        ///Begin
        ///	SELECT *
        ///	FROM AspNetUsers
        ///END.
        /// </summary>
        public static string ListUsers {
            get {
                return ResourceManager.GetString("ListUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[sp_ListUsers].
        /// </summary>
        public static string ListUsersName {
            get {
                return ResourceManager.GetString("ListUsersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[sp_RandomImage]
        ///
        ///AS
        ///Begin
        ///	SELECT TOP 9 *
        ///	FROM [Products] 
        ///	ORDER BY newid();
        ///END.
        /// </summary>
        public static string RandomImage {
            get {
                return ResourceManager.GetString("RandomImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[sp_RandomImage].
        /// </summary>
        public static string RandomImageName {
            get {
                return ResourceManager.GetString("RandomImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE[dbo].[sp_UpdateRole]
        ///	@name AS NVARCHAR(256)
        ///AS
        ///BEGIN
        ///    UPDATE [dbo].[AspNetRoles] SET  Name=@name
        ///END.
        /// </summary>
        public static string UpdateRole {
            get {
                return ResourceManager.GetString("UpdateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[sp_UpdateRole].
        /// </summary>
        public static string UpdateRoleName {
            get {
                return ResourceManager.GetString("UpdateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE[dbo].[sp_UpdateUserRole]
        ///	@id AS NVARCHAR(256)
        ///AS
        ///BEGIN
        ///    UPDATE [dbo].[AspNetUserRoles] SET  Roleid=@id
        ///END.
        /// </summary>
        public static string UpdateUserRole {
            get {
                return ResourceManager.GetString("UpdateUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[sp_UpdateUserRole].
        /// </summary>
        public static string UpdateUserRoleName {
            get {
                return ResourceManager.GetString("UpdateUserRoleName", resourceCulture);
            }
        }
    }
}
